### PR TITLE
fix: CI auto reply

### PR DESCRIPTION
**Pull request by DevHaoZi**
## 📑 Description
Fix CI auto reply.

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [x] All the tests have passed

### CODE REVIEW

**Comment by DevHaoZi** [comment]
yes, and master also need.

**Comment by hwbrzzl** [comment]
Okay, we can merge this PR to v1.12.x first, then merge v1.12.v to master.

**Comment by DevHaoZi** [comment]
> Okay, we can merge this PR to v1.12.x first, then merge v1.12.v to master.

ok

**Review by hwbrzzl — APPROVED** [review]
LGTM

**Pull request merged**
