### PR TITLE
fix: Update Dockerfile

### PR DESCRIPTION
**Pull request by devhaozi**
Closes # 

## 📑 Description

Fix Dockerfile

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [x] All the tests have passed

### CODE REVIEW

**Review by hwbrzzl — COMMENTED** [review]
Q: Do you test it locally, please? And please create a sub-branch, like: `devhaozi/fix-dockerfile`

**Comment by devhaozi** [comment]
> Q: Do you test it locally, please? And please create a sub-branch, like: `devhaozi/fix-dockerfile`

Not yet, because I basically don’t use docker, waiting for other people’s test feedback.

**Comment by hwbrzzl** [comment]
> > Q: Do you test it locally, please? And please create a sub-branch, like: `devhaozi/fix-dockerfile`
> 
> Not yet, because I basically don’t use docker, waiting for other people’s test feedback.

Okay, let me test it first.

**Review by hwbrzzl — APPROVED** [review]
Perfect

**Pull request merged**
